---
- name: Update apt package index
  ansible.builtin.apt:
    update_cache: true

- name: Install QEMU and related packages
  ansible.builtin.apt:
    name:
      - qemu-kvm
      - libvirt-daemon-system
      - libvirt-clients
      - bridge-utils
      - virt-manager
    state: present

- name: Enable and start libvirtd service
  ansible.builtin.systemd:
    name: libvirtd
    enabled: false
    state: started

- name: Add current user to the libvirt group
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: libvirt
    append: true

- name: Add users to docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: libvirt
    append: true
  loop: "{{ qemu_users }}"
