---
- name: Deploy Polkit template to enable hibernate in KDE
  ansible.builtin.template:
    src: enable-hibernate.pkla.j2
    dest: /etc/polkit-1/localauthority/50-local.d/enable-hibernate.pkla
    owner: root
    group: root
    mode: "0644"
