---
- name: Configure Hibernate in the system with battery monitoring service
  ansible.builtin.include_tasks: hibernate/main.yml

- name: Display success message
  ansible.builtin.debug:
    msg: Hibernate configuration completed. System needs to reboot.
