---
- name: Enable Hibernate on experimental ZFS with encryption systems
  ansible.builtin.include_tasks: configure_upower.yml

- name: Configure hibernate and in the system (turn off swap and use it only for hibernate)
  ansible.builtin.include_tasks: configure_hibernate.yml
