---
- name: Add NVIDIA repository
  community.general.zypper:
    name:
      - openSUSE-repos-Tumbleweed-NVIDIA
    state: present
  become: true
  tags:
    - nvidia_driver
#
# - name: "Refresh zypper repositories"
#   community.general.zypper:
#   become: true
#   tags:
#     - nvidia_driver

- name: Install NVIDIA driver packages
  community.general.zypper:
    update_cache: yes
    name:
      - nvidia-gl-G06
      - nvidia-video-G06
    state: present
  become: true
  tags:
    - nvidia_driver

- name: Install SUSE Prime and bbswitch
  community.general.zypper:
    update_cache: yes
    name:
      - suse-prime
      - bbswitch-kmp-default
    state: present
  become: true
  tags:
    - nvidia_driver
