---
- name: Install NVIDIA driver
  ansible.builtin.package:
    name:
      - akmod-nvidia
      - xorg-x11-drv-nvidia-cuda
      - xorg-x11-drv-nvidia-power
    state: present
  tags:
    - nvidia_driver
