users:
  - artem
  - crypto

regular_user_groups: cdrom,dip,plugdev,lpadmin,audio,plugdev,users

sudo_users: []

docker_users:
  - artem

# NOTE: please monitor and keep it up to date with latest version available
# through LLVM official repository - https://apt.llvm.org/, considering of
# course your own needs.
# You can install multiply LLVM versions
llvm_versions:
  - 20

jdk_versions:
  - 21
