---
battery_critical_level: 8

users:
  - artem
  - crypto

regular_user_groups: cdrom,dip,plugdev,lpadmin,audio,users

sudo_users: []
docker_users:
  - artem
qemu_users:
  - artem

# System
## swap
cryptswap_name: cryptswap
swap_mapper_device: "/dev/mapper/{{ cryptswap_name }}"
## hibernate
crypthibernate_name: crypthibernate
hibernate_mapper_device: "/dev/mapper/{{ crypthibernate_name }}"

# NOTE: please monitor and keep it up to date with latest version available
# through LLVM official repository - https://apt.llvm.org/, considering of
# course your own needs.
# You can install multiply LLVM versions
llvm_versions:
  - 20

jdk_versions:
  - 21
