---
battery_critical_level: 8
battery_level_check_interval: 30 # in seconds

users:
  - artem
  - crypto

sudo_users: []
docker_users:
  - artem
qemu_users:
  - artem

# System
## swap
cryptswap_name: swap
swap_mapper_device: "/dev/disk/by-label/{{ cryptswap_name }}"
## hibernate
crypthibernate_name: hibernate
hibernate_mapper_device: "/dev/disk/by-label/{{ crypthibernate_name }}"

# NOTE: please monitor and keep it up to date with latest version available
# through LLVM official repository - https://apt.llvm.org/, considering of
# course your own needs.
# You can install multiply LLVM versions
llvm_versions:
  - 21

jdk_versions:
  - 21

# AWS CLI
sam_cli_zip_url: https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip

# LunarG Vulkan SDK
vulkan_sdk_version: "1.4.304.1"
vulkan_sdk_install_dir: "/opt/vulkansdk"

rpm_based_pkg_managers: ["dnf", "dnf5", "yum", "zypper"]
deb_based_pkg_managers: ["apt"]
