---
# trunk-ignore(checkov/CKV2_ANSIBLE_1)
- name: Fetch the content of the Chromium directory listing
  ansible.builtin.uri:
    url: http://packages.linuxmint.com/pool/upstream/c/chromium/
    return_content: true
  register: page_content

- name: Find all .deb files for 'xia' (Ubuntu 24.04 LTS)
  ansible.builtin.set_fact:
    chromium_versions_list: "{{ page_content.content | regex_findall('chromium_(\\d+[\\.\\d+]*)~linuxmint1\\+xia_amd64\\.deb') }}"

- name: Debug the chromium_versions_list
  ansible.builtin.debug:
    var: chromium_versions_list

- name: Set the latest version of the deb package
  ansible.builtin.set_fact:
    latest_version: "{{ chromium_versions_list | sort | last }}"

- name: Debug the latest_version
  ansible.builtin.debug:
    var: latest_version

- name: Construct the download URL for the latest deb package
  ansible.builtin.set_fact:
    latest_deb_url: http://packages.linuxmint.com/pool/upstream/c/chromium/chromium_{{ latest_version }}~linuxmint1+xia_amd64.deb

- name: Debug the latest .deb URL
  ansible.builtin.debug:
    var: latest_deb_url

- name: Download the latest Chromium .deb package
  ansible.builtin.get_url:
    url: "{{ latest_deb_url }}"
    dest: /tmp/chromium_latest.deb
    mode: "0644"

- name: Install the downloaded Chromium package
  ansible.builtin.apt:
    deb: /tmp/chromium_latest.deb

- name: Remove the downloaded Chromium .deb package
  ansible.builtin.file:
    path: /tmp/chromium_latest.deb
    state: absent
