# Use the Kali Linux rolling image
FROM kalilinux/kali-rolling

# Install a lightweight desktop environment (Xfce), TigerVNC, etc.
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
      tigervnc-standalone-server \
      mate-desktop-environment \
      iproute2 iputils-ping nmap \
    && apt-get clean

RUN set -eux; \
  useradd \
    --no-log-init \
    --base-dir / \
    --home-dir "/work" \
    --create-home \
    --no-user-group \
    --groups sudo,adm \
    --shell "/bin/bash" \
    --uid "65532" \
    user \
  ; \
  passwd \
    --delete \
    --expire \
    user \
  ;

# do this before dropping privileges
COPY ["entrypoint.sh.mate", "/"]
RUN chmod a+x /entrypoint.sh.mate

USER user

WORKDIR /work
ENTRYPOINT ["/entrypoint.sh.mate"]
