- name: Update apt cache
  apt:
    update_cache: yes

- name: Install basic utilities
  apt:
    name:
      - curl
      - wget
      - lsb-release
    state: present

- name: Add multiverse repository
  apt_repository:
    repo: "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) multiverse"
    state: present

- name: Install software packages
  apt:
    name: "{{ software_packages }}"
    state: present

- name: Reconfigure libdvd-pkg
  command: dpkg-reconfigure libdvd-pkg
  when: "'libdvd-pkg' in software_packages"
