---
- name: Create systemd sleep configuration directory
  file:
    path: /etc/systemd/sleep.conf.d/
    state: directory
    mode: '0755'

- name: Configure systemd to enable hibernation without ACPI S4
  copy:
    dest: /etc/systemd/sleep.conf.d/override.conf
    content: |
      [Sleep]
      HibernateMode=platform shutdown
      HibernateState=disk
    mode: '0644'

- name: Restart systemd-logind to apply hibernation configuration
  systemd:
    name: systemd-logind
    state: restarted
