- name: Install uswsusp for software-based hibernate
  apt:
    name: uswsusp
    state: present

- name: Configure uswsusp to handle hibernation
  copy:
    dest: /etc/uswsusp.conf
    content: |
      # Configuration file for s2disk, a part of uswsusp
      snapshot device = /dev/snapshot
      resume device = /dev/disk/by-uuid/{{ swap_uuid }}  # Assuming swap_uuid is set elsewhere in the playbook
      compress = y
      early writeout = y
      image size = 2000000000
      shutdown method = platform
    owner: root
    group: root
    mode: '0644'

# - name: Test software-based hibernate (s2disk)
#   command: s2disk
#   ignore_errors: true
