---
- name: Check if AWS CLI is installed
  ansible.builtin.command: aws --version
  register: aws_cli_check
  ignore_errors: true
  changed_when: false # Prevents the task from being marked as changed
  tags:
    - awscli

- name: Install AWS CLI
  ansible.builtin.import_tasks: awscli_install.yml
  when: aws_cli_check.failed
  tags:
    - awscli
