---
- name: Remove AWS CLI installer and source files
  ansible.builtin.file:
    path: "{{ aws_cli_zip_path }}"
    state: absent

- name: Remove unzipped installer directory
  ansible.builtin.file:
    path: "{{ aws_cli_extract_path }}"
    state: absent
