- name: Remove AWS CLI installer and source files
  file:
    path: "{{ aws_cli_zip_path }}"
    state: absent

- name: Remove unzipped installer directory
  file:
    path: "{{ aws_cli_extract_path }}"
    state: absent
