---
- name: Check if SAM CLI is installed
  ansible.builtin.command: sam --version
  register: sam_cli_check
  ignore_errors: true
  changed_when: false # Prevents the task from being marked as changed
  tags:
    - awscli

- name: Install SAM CLI
  ansible.builtin.import_tasks: sam_install.yml
  when: sam_cli_check.failed
  tags:
    - awscli
