---
# ---------------------------------------------------------
# AUDIO UTILITIES
# ---------------------------------------------------------
- name: Install Audio Utilities
  become: true
  ansible.builtin.package:
    name:
      - carla # May provide both 'Carla (Plugin Host)' & 'Carla Control'
      - carla-control # If separate in your distro
      - fmit # Musical Instrument Tuner
    state: present
  tags:
    - creative_studio

# ---------------------------------------------------------
# EFFECTS
# ---------------------------------------------------------
- name: Install Audio Effects
  become: true
  ansible.builtin.package:
    name:
      - lsp-plugins # LSP Plugins
      # - at1 # JACK autotuner (package may be named 'autotalent' or 'at1')
      - rakarrack
      - zita-rev1
      - guitarix
    state: present
  tags:
    - creative_studio

# ---------------------------------------------------------
# INSTRUMENTS
# ---------------------------------------------------------
- name: Install Synths/Instruments
  become: true
  ansible.builtin.package:
    name:
      # - aeolus
      # - hexter
      - phasex
      - yoshimi
      - zynaddsubfx
      # Some distros split ZynAddSubFX into multiple packages (e.g., zynaddsubfx-jack, zynaddsubfx-alsa)
    state: present
  tags:
    - creative_studio

# ---------------------------------------------------------
# MIDI UTILITIES
# ---------------------------------------------------------
- name: Install MIDI Utilities
  become: true
  ansible.builtin.package:
    name:
      # - gmidimonitor # Some distros might call it 'gmidi-monitor'
      - kmidimon
      - vmpk # Virtual MIDI Keyboard
      - qmidiarp
      # - qmidinet # TODO: install from tarball
      # - qmidiroute
      - qsynth
      - qjackctl # Also used for JACK control
      # - mcpdisp # MIDI control panel display?
      # - mcpdisp-ext
      - qpwgraph # PipeWire graph/patchbay (if using PipeWire)
    state: present
  tags:
    - creative_studio

# ---------------------------------------------------------
# MIXERS AND CARD CONTROL
# ---------------------------------------------------------
- name: Install Mixers and Card Control Tools
  become: true
  ansible.builtin.package:
    name:
      - echomixer # For Echo Digital Audio sound cards
      - ffado-mixer # FireWire audio mixer
      - hdajackretask
      - hdspconf
      - hdspmixer
      - jack-mixer
      - mixxx # Digital DJ
      - mudita24 # ALSA GUI for Envy24
      - qasconfig
      - qashctl
      - qasmixer
      - rmedigicontrol
      # 'Ubuntu Studio Audio Configuration' might be ubuntu-specific (ansible.builtin.package: 'ubuntustudio-controls')
    state: present
  tags:
    - creative_studio

# ---------------------------------------------------------
# MONITORING / LEVEL METERS
# ---------------------------------------------------------
- name: Install Audio Monitoring Tools
  become: true
  ansible.builtin.package:
    name:
      - zita-rev1
      - zita-resampler
      - zita-at1
      - zita-ajbridge
      # - zita-mu1 # Stereo monitoring app # TODO: build from source
      - meterbridge # Audio level meter
    state: present
  tags:
    - creative_studio

# ---------------------------------------------------------
# DAWs and Related Tools
# ---------------------------------------------------------
- name: Install DAWs & Sound Editors
  become: true
  ansible.builtin.package:
    name:
      - ardour8
      - audacity
      # - dgedit # TODO: find, or build from source
      # - envy24control # Possibly part of mudita24
      - mudita24
      - fluidsynth
      # - fluidsynth-dssi # TODO: install from tarball
      # - geonkick # TODO: install from tarball or build from source
      - hydrogen
      - kid3-qt
      - lmms
      - musescore
      # - patchance # TODO: build find source or find package
      # - puredata # TODO: install from Flatpak
      - qtractor
      - raysession
      - sooperlooper
      # The user also has 'mcpdisp-ext', 'qpwgraph' repeated above
    state: present
  tags:
    - creative_studio

# Optionally include JACK / PulseAudio / PipeWire bridging packages:
- name: Install JACK/PipeWire bridging packages
  become: true
  ansible.builtin.package:
    name:
      - pulseaudio-module-jack
      # - pipewire-audio-client-libraries
      # - pipewire-jack-audio-connection-kit
      - pipewire
      - pipewire-alsa
      # Adjust to your distro
    state: present
  tags:
    - creative_studio
