---
# TODO: move it to separate tasks file (codecs or so)
- name: Switch to full ffmpeg
  command: >
    dnf swap -y ffmpeg-free ffmpeg --allowerasing
  tags:
    - creative_studio

- name: Install additional codec (This will allows the application using the gstreamer framework and other multimedia software, to play others restricted codecs)
  command: >
    dnf update -y @multimedia --setopt="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin
  tags:
    - creative_studio

- name: Install Video Production / Editing Tools
  become: true
  package:
    name:
      - blender # Also listed in Graphic/3D, but repeated by some distros
      - devedeng
      # - freeshow # TODO: https://freeshow.app/downloads
      - k3b # CD/DVD burning
      - kdenlive
      - obs-studio
      - openlp # Church lyrics projection
      # - qlcplus # Q Light Controller Plus # TODO: install from here - https://www.qlcplus.org/download
      # - qprompt # TODO: https://qprompt.app/ - Flatpak or so
      - subtitleeditor
      # - xjadeo # TODO: install from tarball - http://xjadeo.sourceforge.net/download.html
      # ...
    state: present
  tags:
    - creative_studio
