---
# NOTE: BastilleLinux is for advanced users only. It can be dangerous a break/damage your system
# - name: Ensure Universe repository is enabled
#   ansible.builtin.apt_repository:
#     repo: "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe"
#     state: present

# - name: Update APT package cache
#   ansible.builtin.apt:
#     update_cache: true

# - name: Install Bastille (system hardening tool)
#   ansible.builtin.package:
#     name: bastille
#     state: present

- name: Install Auditd and Audit plugins
  ansible.builtin.package:
    name:
      - auditd
      - audispd-plugins
    state: present

- name: Deploy auditd configuration file
  ansible.builtin.template:
    src: auditd.conf.j2
    dest: /etc/audit/auditd.conf
    mode: "0644"

- name: Deploy audit rules file
  ansible.builtin.template:
    src: workstation.rules.j2
    dest: /etc/audit/rules.d/workstation.rules
    mode: "0644"

- name: Reload auditd rules
  ansible.builtin.command: augenrules --load
  register: auditd_reload_result
  changed_when: "'No rules' not in auditd_reload_result.stdout"

- name: Restart auditd service
  ansible.builtin.systemd:
    name: auditd
    state: restarted
    enabled: true
# - name: Install AppArmor and AppArmor utilities
#   ansible.builtin.package:
#     name:
#       - apparmor
#       - apparmor-utils
#     state: present

# - name: Install UFW firewall
#   ansible.builtin.package:
#     name: ufw
#     state: present
