---
- name: Configure System to Install Thunderbird from Mozilla PPA
  ansible.builtin.include_tasks: ubuntu/thunderbird_ppa.yml
  when:
    - thunderbird_mozilla_ppa
  tags:
    - mail_client

- name: Configure System to Install Thunderbird from Snap
  ansible.builtin.include_tasks: ubuntu/thunderbird_snap.yml
  when:
    - not thunderbird_mozilla_ppa
  tags:
    - mail_client
