- name: Add multiverse repository
  apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu {{ ansible_facts.distribution_release }} multiverse
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install basic utilities
  apt:
    name:
      - curl
      - wget
    state: present

- name: Install system software packages
  apt:
    name:
      - nvidia-prime
      - build-essential
      - git
      - mpv
      - pkg-config
      - libssl-dev
      - htop
      - apt-transport-https
      - synaptic
    state: present

- name: Install proprietary codecs and fonts
  apt:
    name:
      - ubuntu-restricted-extras
      - gstreamer1.0-libav
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - libdvd-pkg
    state: present

- name: Pre-configure libdvd-pkg for non-interactive installation
  debconf:
    name: libdvd-pkg
    question: libdvd-pkg/build
    value: true
    vtype: boolean

- name: Reconfigure libdvd-pkg non-interactively
  environment:
    DEBIAN_FRONTEND: noninteractive
  command: dpkg-reconfigure libdvd-pkg
