---
- name: Add Debian repository with contrib and non-free components
  ansible.builtin.apt_repository:
    repo: "deb http://deb.debian.org/debian {{ ansible_facts.distribution_release }} main contrib non-free"
    state: present

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install basic utilities
  ansible.builtin.apt:
    name:
      - curl
      - wget
    state: present

- name: Install system software packages
  ansible.builtin.apt:
    name:
      - build-essential
      - git
      - unzip
      - mpv
      - pkg-config
      - libssl-dev
      - htop
      - apt-transport-https
      - synaptic
    state: present

- name: Install proprietary codecs and fonts
  ansible.builtin.apt:
    name:
      - gstreamer1.0-libav
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - libdvd-pkg
      - ttf-mscorefonts-installer
    state: present

- name: Pre-configure libdvd-pkg for non-interactive installation
  ansible.builtin.debconf:
    name: libdvd-pkg
    question: libdvd-pkg/build
    value: true
    vtype: boolean

- name: Reconfigure libdvd-pkg non-interactively
  ansible.builtin.command: dpkg-reconfigure libdvd-pkg
  environment:
    DEBIAN_FRONTEND: noninteractive
  changed_when: true

- name: Install Python virtual environment support
  ansible.builtin.apt:
    name:
      - python3-venv
    state: present
