# roles/wine/tasks/distros/fedora.yml
---
- name: Check if Brave repository exists
  ansible.builtin.stat:
    path: /etc/yum.repos.d/winehq.repo
  register: winehq_repo
  tags:
    - wine

- name: Add WineHQ repository (Fedora 41+)
  ansible.builtin.command: dnf5 config-manager addrepo --from-repofile=https://dl.winehq.org/wine-builds/fedora/{{ ansible_facts['distribution_major_version'] }}/winehq.repo
  when:
    - ansible_facts['distribution_major_version'] | int >= 41
    - not winehq_repo.stat.exists
  become: true
  tags:
    - wine

- name: Add WineHQ repository (Fedora 40)
  ansible.builtin.command: dnf config-manager --add-repo https://dl.winehq.org/wine-builds/fedora/{{ ansible_facts['distribution_major_version'] }}/winehq.repo
  when:
    - ansible_facts['distribution_major_version'] | int == 40
    - not winehq_repo.stat.exists
  become: true
  tags:
    - wine
