---
- name: Install Midnight Commander
  ansible.builtin.package:
    name: mc
    state: present
  tags:
    - file_managers

- name: Install Krusader file manager
  ansible.builtin.package:
    name:
      - krusader
      - krename
    state: present
  tags:
    - file_managers
