- name: Add Brave browser repository key
  apt_key:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    keyring: /etc/apt/keyrings/brave-browser-archive-keyring.gpg
    state: present

- name: Add Brave browser repository
  apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Brave browser
  apt:
    name:
      - brave-browser
    state: present
