# roles/brave/tasks/distros/distro_prepare.yml
---
- name: Ubuntu math packages
  ansible.builtin.include_tasks: distros/ubuntu.yml
  when: ansible_facts['distribution'] == "Ubuntu"
  tags:
    - math

- name: Fedora math packages
  ansible.builtin.include_tasks: distros/fedora.yml
  when: ansible_facts['distribution'] == "Fedora"
  tags:
    - math
