---
- name: Ensure UPower is installed
  ansible.builtin.package:
    name: upower
    state: present

- name: Configure UPower to hibernate on critical battery level
  ansible.builtin.template:
    src: upower.conf.j2
    dest: /etc/UPower/UPower.conf
    mode: "0644"
    backup: true

- name: Restart UPower service
  ansible.builtin.systemd:
    name: upower
    state: restarted

- name: Ensure UPower is enabled on startup
  ansible.builtin.systemd:
    name: upower
    enabled: true
    state: started

- name: Deploy force-hibernate.sh script
  ansible.builtin.template:
    src: force-hibernate.sh.j2
    dest: /usr/local/bin/force-hibernate.sh
    owner: root
    group: root
    mode: "0755"

- name: Deploy systemd-sleep script to disable swap for hibernation after system
  ansible.builtin.template:
    src: swapoff-hibernate.sh.j2
    dest: /usr/lib/systemd/system-sleep/swapoff-hibernate.sh
    owner: root
    group: root
    mode: "0755"

- name: Deploy systemd service unit for force-hibernate
  ansible.builtin.template:
    src: force-hibernate.service.j2
    dest: /etc/systemd/system/force-hibernate.service
    owner: root
    group: root
    mode: "0644"

- name: Deploy systemd timer unit for force-hibernate
  ansible.builtin.template:
    src: force-hibernate.timer.j2
    dest: /etc/systemd/system/force-hibernate.timer
    owner: root
    group: root
    mode: "0644"

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start force-hibernate timer
  ansible.builtin.systemd:
    name: force-hibernate.timer
    enabled: true
    state: stopped

- name: Enable and start force-hibernate timer
  ansible.builtin.systemd:
    name: force-hibernate.timer
    enabled: true
    state: started
