---
- name: VPN tools (Ubuntu)
  ansible.builtin.include_tasks: ubuntu/vpn_ubuntu.yml
  when: ansible_facts['distribution'] == "Ubuntu"
  tags: [vpn]

- name: VPN tools (Fedora)
  ansible.builtin.include_tasks: fedora/vpn_fedora.yml
  when: ansible_facts['distribution'] == "Fedora"
  tags: [vpn]
