---
- name: Install WireGuard
  ansible.builtin.apt:
    name:
      - wireguard
    state: present
  tags:
    - vpn

- name: Install OpenVPN
  ansible.builtin.apt:
    name:
      - openvpn
      - network-manager-openvpn
    state: present
  tags:
    - vpn
