---
- name: Add LLVM repository key
  ansible.builtin.apt_key:
    url: https://apt.llvm.org/llvm-snapshot.gpg.key
    keyring: /etc/apt/keyrings/llvm-archive-keyring.gpg
    state: present

- name: Add LLVM binary repository
  ansible.builtin.apt_repository:
    repo: >
      deb [signed-by=/etc/apt/keyrings/llvm-archive-keyring.gpg]
      http://apt.llvm.org/{{ ansible_facts.distribution_release }}/
      llvm-toolchain-{{ ansible_facts.distribution_release }} main
    state: present

- name: Add LLVM source repository
  ansible.builtin.apt_repository:
    repo: >
      deb-src [signed-by=/etc/apt/keyrings/llvm-archive-keyring.gpg]
      http://apt.llvm.org/{{ ansible_facts.distribution_release }}/
      llvm-toolchain-{{ ansible_facts.distribution_release }} main
    state: present

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

# TODO: I decided not to install meta packages, because there is a problem
# with some packages like libpolly, for example. It does not have meta package,
# so if you want to use it (most probably you are if go crazy with
# cache locality optimizations), then you need to explicitly specify its
# version anyways, like libpolly-20-dev (latest on time of writing).
# And its not the only problematic package. So I decided to go with list
# of LLVM verstion you want to install. Just configure your software to use
# "clang-<version>" instead of "clang", "clangd", "clang-tidy". So it will be
# "clang-20", "clangd-20", "clang-tidy-20", etc.

# - name: Install all LLVM packages (meta packages)
#   apt:
#     name:
#       - clang-format
#       - clang-tidy
#       - clang-tools
#       - clang
#       - clangd
#       - libc++-dev
#       - libc++1
#       - libc++abi-dev
#       - libc++abi1
#       - libclang-dev
#       # - libclang-common-dev
#       - libclang-cpp-dev
#       # - libunwind-dev
#       - libclang1
#       - liblldb-dev
#       - libllvm-ocaml-dev
#       - libomp-dev
#       - lld
#       - lldb
#       - llvm-dev
#       - llvm-runtime
#       # - llvm-tools
#       - libomp-dev
#       - llvm
#       - python3-clang
#       - libclang-rt-dev
#       # - libpolly-dev
#     state: present

# There is a problem, at least with one package - libpolly-20-dev - there is
# no meta-package for it. And nothing depend on it. So you must specify its
# version explicitly. But how to make it, if you don't know what is current
# LLVM release. Its LLVM repo problem. Hope they will fix it. For now I'm
# installing meta-packages (latest LLVM repo versions) + specific version
# packages in order to get libpolly-dev also available
- name: Install all LLVM packages (versioned ones)
  ansible.builtin.apt:
    name:
      - clang-format-{{ item }}
      - clang-tidy-{{ item }}
      - clang-tools-{{ item }}
      - clang-{{ item }}
      - clangd-{{ item }}
      - libc++-{{ item }}-dev
      - libc++1-{{ item }}
      - libc++abi-{{ item }}-dev
      - libc++abi1-{{ item }}
      - libclang-{{ item }}-dev
      - libclang-common-{{ item }}-dev
      - libclang-cpp{{ item }}-dev
      - libunwind-{{ item }}-dev
      - libclang1-{{ item }}
      - liblldb-{{ item }}-dev
      - libllvm-{{ item }}-ocaml-dev
      - libomp-{{ item }}-dev
      - lld-{{ item }}
      - lldb-{{ item }}
      - llvm-{{ item }}-dev
      - llvm-{{ item }}-runtime
      - llvm-{{ item }}-tools
      - libomp-{{ item }}-dev
      - llvm-{{ item }}
      - python3-clang-{{ item }}
      - libclang-rt-{{ item }}-dev
      - libpolly-{{ item }}-dev
    state: present
  loop: "{{ llvm_versions }}"
