- name: Check if user {{ item }} exists
  command: id {{ item }}
  register: user_exists
  ignore_errors: true

- name: Ensure ZFS dataset and user setup for {{ item }}
  block:
    - name: Create ZFS dataset for user {{ item }}
      command: zfs create rpool/USERDATA/home_{{ item }}

    - name: Set ZFS mountpoint for user {{ item }}
      command: zfs set mountpoint=/home/{{ item }} rpool/USERDATA/home_{{ item }}

    - name: Create user {{ item }}
      user:
        name: "{{ item }}"
        groups: "{{ regular_user_groups }}"
        shell: /bin/bash
        create_home: true

    - name: Set ownership and permissions for /home/{{ item }}
      file:
        path: "/home/{{ item }}"
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: "0700"

  when: user_exists.rc != 0
  rescue:
    - name: Handle failure by logging
      debug:
        msg: "Failed to fully process {{ item }} user successfully"
  always:
    - name: Ensure task cleanup is done
      debug:
        msg: "Task execution complete for {{ item }}."
