---
#- name: Ensure ZFS is installed
#  ansible.builtin.apt:
#    name: zfsutils-linux
#    state: present

- name: Create users with ZFS datasets
  ansible.builtin.include_tasks: create_user.yml
  loop: "{{ users }}"

- name: Add users in the sudo group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: sudo
    append: true
  loop: "{{ sudo_users }}"
