- name: Ensure ZFS is installed
  apt:
    name: zfsutils-linux
    state: present

- name: Create users with ZFS datasets
  include_tasks: create_user.yml
  loop: "{{ users }}"

- name: Add users in the sudo group
  user:
    name: "{{ item }}"
    groups: sudo
    append: yes
  loop: "{{ sudo_users }}"
