---
- name: NVIDIA Prime Run script
  template:
    src: prime_run_wayland.sh.j2
    dest: /usr/local/bin/prime-run-wayland.sh
    owner: root
    group: root
    mode: "0755"
  become: true
  tags:
    - prime_run
