---
- name: Update apt package index
  ansible.builtin.apt:
    update_cache: true

- name: Install VirtualBox
  ansible.builtin.apt:
    name:
      - virtualbox
      - virtualbox-guest-additions-iso
    state: present
