---
- name: Vulkan SDK Install (Ubuntu)
  ansible.builtin.include_tasks: ubuntu/vulkan_sdk_ubuntu.yml
  when: ansible_facts['distribution'] == "Ubuntu"
  tags:
    - vulkan_sdk

- name: Vulkan SDK Install (Ubuntu)
  ansible.builtin.include_tasks: ubuntu/vulkan_sdk_ubuntu.yml
  when: ansible_facts['distribution'] == "Pop!_OS"
  tags:
    - vulkan_sdk

- name: Vulkan SDK Install (Tarball)
  ansible.builtin.include_tasks: others/vulkan_sdk_others.yml
  when:
    - ansible_facts['distribution'] != "Ubuntu"
    - ansible_facts['distribution'] != "Pop!_OS"
  tags:
    - vulkan_sdk
