---
- name: Replace the crypttab entry with a keyfile-based swap configuration
  ansible.builtin.lineinfile:
    path: /etc/crypttab
    regexp: .*swap.*urandom.*
    line: dm_crypt-0 {{ crypttab_uuid.stdout }} /root/swap_keyfile swap,initramfs
    state: present
    backup: true

- name: Regenerate initramfs
  ansible.builtin.command: update-initramfs -u
  changed_when: true
