---
- name: Create hibernate configuration script from template
  ansible.builtin.template:
    src: hibernate_configure.sh.j2
    dest: /root/hibernate_configure.sh
    mode: "0755"

- name: Create systemd service for hibernate configuration from template
  ansible.builtin.template:
    src: hibernate-configure.service.j2
    dest: /etc/systemd/system/hibernate-configure.service
    mode: "0644"

- name: Enable, and start hibernate configuration service
  ansible.builtin.systemd:
    name: hibernate-configure.service
    enabled: true
    state: started
