---
- name: Ensure i386 architecture is enabled (for 64-bit systems)
  ansible.builtin.command: dpkg --add-architecture i386
  when: ansible_architecture == 'x86_64'
  become: true
  tags:
    - wine

- name: Download and add the WineHQ repository key
  ansible.builtin.apt_key:
    url: https://dl.winehq.org/wine-builds/winehq.key
    keyring: /etc/apt/keyrings/winehq-archive.key
    state: present
  tags:
    - wine

- name: Add the WineHQ repository for Debian Bookworm
  ansible.builtin.get_url:
    url: https://dl.winehq.org/wine-builds/debian/dists/bookworm/winehq-bookworm.sources
    dest: /etc/apt/sources.list.d/winehq-bookworm.sources
  become: true
  tags:
    - wine

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true
  tags:
    - wine

- name: Install WineHQ Staging
  ansible.builtin.apt:
    name: winehq-staging
    state: present
    install_recommends: true
  become: true
  tags:
    - wine
