---
- name: Install WineHQ Staging
  ansible.builtin.package:
    name:
      - winehq-staging
      - lutris
      - playonlinux
    state: present
  become: true
  when: ansible_facts['distribution'] == "Ubuntu"
  tags:
    - wine

# TODO: Lutris and Playonlinux conflict with winehq; need to resolve it somehow
- name: Install WineHQ Staging
  ansible.builtin.package:
    name:
      - winehq-staging
    state: present
  become: true
  when: ansible_facts['distribution'] == "Fedora"
  tags:
    - wine
