---

- name: Install Wine
  ansible.builtin.apt:
    name:
      - wine
      - winbind
      - winetricks
    state: present
  tags:
    - wine

- name: Install Lutris
  ansible.builtin.apt:
    name:
      - lutris
    state: present
  tags:
    - wine

- name: Install PlayOnLinux
  ansible.builtin.apt:
    name:
      - playonlinux
    state: present
  tags:
    - wine
