---
- name: Install Docker packages
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Add users to docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_users }}"

- name: Keep Docker services disabled by default (they will be started automatically on-demand)
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: false
    state: stopped
  loop:
    - docker.service
    - containerd.service
