---
- name: Ensure i386 architecture is enabled (for 64-bit systems)
  ansible.builtin.command: dpkg --add-architecture i386
  when: ansible_architecture == 'x86_64'
  become: true
  tags:
    - wine

- name: Download and add the WineHQ repository key
  ansible.builtin.apt_key:
    url: https://dl.winehq.org/wine-builds/winehq.key
    keyring: /etc/apt/keyrings/winehq-archive.key
    state: present
  tags:
    - wine

- name: Add the WineHQ repository (Ubuntu "{{ ansible_facts.distribution_release }}")
  ansible.builtin.get_url:
    url: "https://dl.winehq.org/wine-builds/ubuntu/dists/{{ ansible_facts.distribution_release }}/winehq-{{ ansible_facts.distribution_release }}.sources"
    dest: "/etc/apt/sources.list.d/winehq-{{ ansible_facts.distribution_release }}.sources"
  become: true
  tags:
    - wine

- name: Install WineHQ Staging
  ansible.builtin.apt:
    update_cache: true
    name:
      - winehq-staging
      - lutris
      - playonlinux
    state: present
  become: true
  tags:
    - wine
