---
- name: Workstation Initialization
  hosts: localhost
  become: true
  gather_facts: true

- name: Configure Power Management
  import_playbook: configure_power_management.yml
- name: Setup Users
  import_playbook: workstation_users.yml
- name: Install System Software
  import_playbook: workstation_system.yml
- name: Developer Software Packages
  import_playbook: workstation_software.yml
- name: Security Audit Software
  import_playbook: software_security_audit.yml
- name: Secure settings for Workstation
  import_playbook: secure_workstation.yml
