---
- name: Workstation Software Installation
  hosts: localhost
  become: true
  gather_facts: true
  roles:
    - ansible_lint
    - bazel
    - brave
    - docker
    - llvm
    - sublime
    - trunk_io
    - vscode
    - vulkan_sdk
    - awscli
    - jdk
    - cmake
    - chromium
    - qemu
    - virtualbox
    - disk_usage
    - stress_tests
    - file_monitoring
    - torrent_clients
    - wine
    - profilers
