---
# TODO: Ubuntu built-in version is too old and not supported by VSCode plugin
# - name: Install Neovim
#   ansible.builtin.apt:
#     name:
#       - neovim
#       - neovim-qt
#     state: present

- name: Ensure /opt exists
  file:
    path: /opt
    state: directory
    mode: "0755"
  tags:
    - neovim

- name: Download the latest Neovim binary
  get_url:
    url: https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz
    dest: /tmp/nvim-linux-x86_64.tar.gz
    mode: "0644"
  tags:
    - neovim

- name: Remove old Neovim installation
  file:
    path: /opt/nvim-linux-x86_64
    state: absent
  tags:
    - neovim

- name: Extract Neovim to /opt
  ansible.builtin.unarchive:
    src: /tmp/nvim-linux-x86_64.tar.gz
    dest: /opt
    remote_src: yes
    extra_opts: [--strip-components=0]
    mode: "0755"
  tags:
    - neovim

- name: Ensure symlink exists in /usr/local/bin
  file:
    src: /opt/nvim-linux-x86_64/bin/nvim
    dest: /usr/local/bin/nvim
    state: link
  tags:
    - neovim
