---
- name: Ensure required packages are installed for building Neovim-Qt
  ansible.builtin.apt:
    name:
      - cmake
      - build-essential
      - qt5-qmake
      - qt5-qmake-bin
      - qtbase5-dev
      - qtbase5-dev-tools
      - libqt5svg5-dev
      - qtchooser
      - libqt5concurrent5
      - libqt5core5a
      - libqt5dbus5
      - libqt5gui5
      - libqt5network5
      - libqt5widgets5
      - libqt5xml5
    state: present
  become: true
  tags:
    - neovim

- name: Clone Neovim-Qt repository
  ansible.builtin.git:
    repo: https://github.com/equalsraf/neovim-qt.git
    dest: /tmp/neovim-qt
    version: master
    update: true
  tags:
    - neovim

- name: Ensure build directory exists
  ansible.builtin.file:
    path: /tmp/neovim-qt/build
    state: directory
    mode: "0755"
  tags:
    - neovim

- name: Run CMake to configure Neovim-Qt build
  ansible.builtin.command:
    cmd: cmake -DCMAKE_BUILD_TYPE=Release ..
    chdir: /tmp/neovim-qt/build
  tags:
    - neovim

- name: Compile Neovim-Qt
  ansible.builtin.command:
    cmd: make -j"{{ ansible_processor_vcpus | default(2) }}"
    chdir: /tmp/neovim-qt/build
  tags:
    - neovim

- name: Install Neovim-Qt
  ansible.builtin.command:
    cmd: make install
    chdir: /tmp/neovim-qt/build
  become: true
  tags:
    - neovim
# - name: Ensure Neovim-Qt symlink exists in /usr/local/bin
#   ansible.builtin.file:
#     src: /usr/local/bin/nvim-qt
#     dest: /usr/local/bin/nvim-qt
#     state: link
#   tags:
#     - neovim-qt
