# roles/brave/tasks/distros/fedora.yml
---
- name: Remove Fedora default packages
  ansible.builtin.package:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-selinux
      - docker-engine-selinux
      - docker-engine
    state: absent
  ignore_errors: yes

- name: "Ensure dnf-plugins-core is installed"
  ansible.builtin.dnf:
    name: dnf-plugins-core
    state: present

- name: "Check if Brave repository exists"
  ansible.builtin.stat:
    path: /etc/yum.repos.d/docker-ce.repo
  register: docker_ce_repo

- name: "Add Docker repository"
  ansible.builtin.command: dnf-3 config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
  when:
    - not docker_ce_repo.stat.exists

- name: Install Docker packages
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
