---
- name: Install entr
  ansible.builtin.package:
    name: entr
    state: present
  tags:
    - file_monitoring_packages
    - entr

- name: Install watchman
  ansible.builtin.package:
    name: watchman
    state: present
  when: ansible_facts['distribution'] == "Ubuntu"
  tags:
    - file_monitoring_packages
    - watchman
# TODO: watchman package is broken in Fedora; compile from sources
