---
- name: Download BRL-CAD archive
  ansible.builtin.get_url:
    url: https://github.com/BRL-CAD/brlcad/releases/download/rel-7-40-2/BRL-CAD_7.40.2_Linux_x86_64.tar.bz2
    dest: /tmp/BRL-CAD_7.40.2_Linux_x86_64.tar.bz2
    mode: "0644"
  tags:
    - cad

- name: Ensure /opt/BRL-CAD directory exists
  ansible.builtin.file:
    path: /opt/BRL-CAD
    state: directory
    mode: "0755"
  tags:
    - cad

- name: Extract BRL-CAD archive to /opt/BRL-CAD
  ansible.builtin.unarchive:
    src: /tmp/BRL-CAD_7.40.2_Linux_x86_64.tar.bz2
    dest: /opt/BRL-CAD
    remote_src: true
    extra_opts: [--strip-components=1]
    creates: /opt/BRL-CAD/bin # The creates option ensures that the task does not re-extract if the target directory already contains the expected files
  tags:
    - cad

- name: Cleanup downloaded archive
  ansible.builtin.file:
    path: /tmp/BRL-CAD_7.40.2_Linux_x86_64.tar.bz2
    state: absent
  tags:
    - cad
