---
- name: Install OpenSCAD
  ansible.builtin.package:
    name:
      - openscad
    state: present
  tags:
    - cad

- name: Install Sweet Home 3D
  ansible.builtin.package:
    name:
      - sweethome3d
    state: present
  tags:
    - cad
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Install Sweet Home 3D via Flatpak (system-wide)
  ansible.builtin.command: >
    flatpak install --assumeyes --system flathub com.sweethome3d.Sweethome3d
  args:
    creates: /var/lib/flatpak/app/com.sweethome3d.Sweethome3d
  when: ansible_facts['distribution'] == "Fedora"
  tags:
    - cad

# - name: Install FreeCAD
#   ansible.builtin.apt:
#     name:
#       - freecad
#     state: present
#   tags:
#     - cad
- name: Install FreeCAD
  ansible.builtin.command: >
    flatpak install --assumeyes --system flathub org.freecad.FreeCAD
  args:
    creates: /var/lib/flatpak/app/org.freecad.FreeCAD
  when: ansible_facts['distribution'] == "Fedora"
  tags:
    - cad

- name: Install LibreCAD
  ansible.builtin.package:
    name:
      - librecad
    state: present
  tags:
    - cad

- name: Install LibreCAD (Fedora specific additions)
  ansible.builtin.package:
    name:
      - librecad-patterns
      - librecad-fonts
      - librecad-langs
      - librecad-parts
    state: present
  when: ansible_facts['distribution'] == "Fedora"
  tags:
    - cad

- name: Check if BRL-CAD is already installed
  ansible.builtin.stat:
    path: /opt/BRL-CAD/bin/brlman
  register: brl_cad_installed

- name: Run BRL-CAD Tarball Installer
  ansible.builtin.include_tasks: brl_cad_install.yml
  when: not brl_cad_installed.stat.exists
  tags:
    - cad
